import type { Alert, Prediction, Sensor, Shelter, Zone } from './types';

const now = new Date().toISOString();

function squarePolygon(lng: number, lat: number, size = 0.045) {
  return {
    type: 'Polygon' as const,
    coordinates: [[
      [lng - size, lat - size],
      [lng + size, lat - size],
      [lng + size, lat + size],
      [lng - size, lat + size],
      [lng - size, lat - size],
    ]],
  };
}

export const mockShelters: Shelter[] = [
  {
    shelter_id: 'mock-shelter-col-01',
    name: 'Colombo Central Evacuation Center',
    capacity: 1200,
    current_occupancy: 420,
    lat: 6.9271,
    lng: 79.8612,
    distance_km: 1.8,
    contact_number: '+94 11 555 0101',
    zone_id: 'mock-zone-kelani',
    status: 'OPEN',
  },
  {
    shelter_id: 'mock-shelter-kdy-01',
    name: 'Kandy Community Hall',
    capacity: 600,
    current_occupancy: 390,
    lat: 7.2936,
    lng: 80.6410,
    distance_km: 2.6,
    contact_number: '+94 81 555 0102',
    zone_id: 'mock-zone-mahaweli',
    status: 'FILLING',
  },
  {
    shelter_id: 'mock-shelter-gal-01',
    name: 'Galle Sports Complex',
    capacity: 800,
    current_occupancy: 760,
    lat: 6.0323,
    lng: 80.2186,
    distance_km: 3.4,
    contact_number: '+94 91 555 0103',
    zone_id: 'mock-zone-gin',
    status: 'FULL',
  },
];

export const mockZones: Zone[] = [
  {
    zone_id: 'mock-zone-kelani',
    zone_name: 'Kelani River Basin',
    description: 'Test zone around Colombo and Kelani basin.',
    risk_level: 'HIGH',
    risk_score: 78,
    color_code: '#F97316',
    population_at_risk: 12400,
    sensors_in_zone: ['MOCK-SEN-001', 'MOCK-SEN-002'],
    active_alerts: 1,
    last_updated: now,
    geometry: squarePolygon(79.93, 6.95, 0.06),
    current_conditions: {
      avg_water_level_m: 2.4,
      max_water_level_m: 3.1,
      avg_flow_velocity_mps: 1.8,
      total_rainfall_mm: 45,
      trend: 'RISING',
    },
    prediction: {
      flood_probability_percent: 82,
      predicted_peak_level_m: 3.6,
      estimated_flood_time: '2026-05-01T18:00:00Z',
      confidence_percent: 88,
      model_version: 'mock-v1',
    },
    shelters: mockShelters.filter((shelter) => shelter.zone_id === 'mock-zone-kelani'),
  },
  {
    zone_id: 'mock-zone-mahaweli',
    zone_name: 'Mahaweli River',
    description: 'Test zone near Kandy and central river basin.',
    risk_level: 'WARNING',
    risk_score: 56,
    color_code: '#EAB308',
    population_at_risk: 8700,
    sensors_in_zone: ['MOCK-SEN-003'],
    active_alerts: 0,
    last_updated: now,
    geometry: squarePolygon(80.64, 7.29, 0.055),
    current_conditions: {
      avg_water_level_m: 1.5,
      max_water_level_m: 2.0,
      avg_flow_velocity_mps: 1.1,
      total_rainfall_mm: 28,
      trend: 'STABLE',
    },
    shelters: mockShelters.filter((shelter) => shelter.zone_id === 'mock-zone-mahaweli'),
  },
  {
    zone_id: 'mock-zone-gin',
    zone_name: 'Gin River',
    description: 'Test zone near Galle and southern basin.',
    risk_level: 'CRITICAL',
    risk_score: 92,
    color_code: '#EF4444',
    population_at_risk: 21000,
    sensors_in_zone: ['MOCK-SEN-004'],
    active_alerts: 2,
    last_updated: now,
    geometry: squarePolygon(80.23, 6.06, 0.055),
    current_conditions: {
      avg_water_level_m: 3.4,
      max_water_level_m: 4.1,
      avg_flow_velocity_mps: 2.6,
      total_rainfall_mm: 78,
      trend: 'RISING',
    },
    shelters: mockShelters.filter((shelter) => shelter.zone_id === 'mock-zone-gin'),
  },
];

export const mockSensors: Sensor[] = [
  {
    sensor_id: 'MOCK-SEN-001',
    name: 'Kelani North Gauge - Colombo',
    location: { lat: 6.961, lng: 79.91, zone_id: 'mock-zone-kelani', zone_name: 'Kelani River Basin' },
    readings: { water_level_m: 2.4, rainfall_mm_per_hr: 45, flow_velocity_mps: 1.8, temperature_c: 29, air_pressure_hpa: 1008 },
    status: { is_online: true, device_online: true, battery_percent: 86, signal_strength_dbm: -62, last_seen: now },
    thresholds: { warning_m: 2.5, critical_m: 3.5 },
    installed_date: '2025-10-01',
    is_active: true,
  },
  {
    sensor_id: 'MOCK-SEN-002',
    name: 'Kelani South Gauge - Hanwella',
    location: { lat: 6.904, lng: 80.08, zone_id: 'mock-zone-kelani', zone_name: 'Kelani River Basin' },
    readings: { water_level_m: 2.1, rainfall_mm_per_hr: 38, flow_velocity_mps: 1.4, temperature_c: 30, air_pressure_hpa: 1007 },
    status: { is_online: true, device_online: true, battery_percent: 72, signal_strength_dbm: -70, last_seen: now },
    thresholds: { warning_m: 2.5, critical_m: 3.5 },
    installed_date: '2025-11-12',
    is_active: true,
  },
  {
    sensor_id: 'MOCK-SEN-003',
    name: 'Mahaweli Gauge - Kandy',
    location: { lat: 7.291, lng: 80.637, zone_id: 'mock-zone-mahaweli', zone_name: 'Mahaweli River' },
    readings: { water_level_m: 1.5, rainfall_mm_per_hr: 28, flow_velocity_mps: 1.1, temperature_c: 27, air_pressure_hpa: 1011 },
    status: { is_online: true, device_online: true, battery_percent: 64, signal_strength_dbm: -68, last_seen: now },
    thresholds: { warning_m: 2.0, critical_m: 3.0 },
    installed_date: '2025-09-18',
    is_active: true,
  },
  {
    sensor_id: 'MOCK-SEN-004',
    name: 'Gin River Gauge - Galle',
    location: { lat: 6.063, lng: 80.24, zone_id: 'mock-zone-gin', zone_name: 'Gin River' },
    readings: { water_level_m: 3.4, rainfall_mm_per_hr: 78, flow_velocity_mps: 2.6, temperature_c: 28, air_pressure_hpa: 1005 },
    status: { is_online: false, device_online: false, battery_percent: 18, signal_strength_dbm: -91, last_seen: '2026-05-01T05:30:00Z' },
    thresholds: { warning_m: 2.5, critical_m: 3.3 },
    installed_date: '2025-08-04',
    is_active: true,
  },
];

export const mockAlerts: Alert[] = [
  {
    alert_id: 'mock-alert-001',
    zone_id: 'mock-zone-gin',
    zone_name: 'Gin River',
    severity: 'CRITICAL',
    severity_code: 5,
    title: 'Critical water level detected',
    message: 'Gin River test sensor reports water level above critical threshold.',
    triggered_at: now,
    triggered_by: 'mock-data',
    status: 'ACTIVE',
    resolved_at: null,
    affected_population: 21000,
    recommended_action: 'Open shelters and begin evacuation readiness checks.',
    recommended_shelters: mockShelters.filter((shelter) => shelter.zone_id === 'mock-zone-gin'),
  },
  {
    alert_id: 'mock-alert-002',
    zone_id: 'mock-zone-kelani',
    zone_name: 'Kelani River Basin',
    severity: 'HIGH',
    severity_code: 4,
    title: 'Rapid rainfall accumulation',
    message: 'Kelani basin test readings show sustained rainfall and rising water trend.',
    triggered_at: now,
    triggered_by: 'mock-data',
    status: 'ACTIVE',
    resolved_at: null,
    affected_population: 12400,
    recommended_action: 'Monitor low-lying roads and prepare evacuation transport.',
    recommended_shelters: mockShelters.filter((shelter) => shelter.zone_id === 'mock-zone-kelani'),
  },
];

export const mockPredictions: Prediction[] = [
  {
    prediction_id: 'mock-pred-001',
    zone_id: 'mock-zone-gin',
    zone_name: 'Gin River',
    created_at: now,
    prediction_window: {
      from: now,
      to: '2026-05-01T20:00:00Z',
    },
    flood_probability_percent: 91,
    predicted_peak_level_m: 4.2,
    estimated_flood_time: '2026-05-01T18:30:00Z',
    severity: 'CRITICAL',
    confidence_percent: 87,
    model_version: 'mock-v1',
    top_risk_factors: [
      { factor: 'Rainfall intensity', value: '78 mm/hr', impact: 'High' },
      { factor: 'River level', value: '3.4 m', impact: 'High' },
    ],
  },
];
