name: flood_frontend
description: Smart Flood Management frontend skeleton
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  geolocator: ^14.0.2
  http: ^1.6.0
  socket_io_client: ^3.1.4
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  clerk_flutter: 0.0.14-beta
  clerk_auth: 0.0.14-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
